{{ $root := . -}}
{{- range $index, $value := .Values.secrets }}
---
apiVersion: v1
kind: Secret
{{ if $value.type }}
type: {{ $value.type }}
{{- end }}
metadata:
  labels: {{ include "secrets.labels" $root | nindent 4 }}
  name: {{ include "secrets.fullname" $root }}-{{ $value.name }}
{{- with $value.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- range $name, $data := $value.data }}
{{ $name | indent 2 }}: {{ $data | b64enc | quote }}
{{- end }}
{{- end }}
