repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: appscode
    url: https://charts.appscode.com/stable/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: banzicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
  - name: cloudposse-incubator
    url: https://charts.cloudposse.com/incubator/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

templates:
  default: &default
    missingFileHandler: Warn
    values:
    - configs/{{`{{ .Release.Name }}`}}/values.yaml
    - configs/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
    secrets:
    - secrets/{{`{{ .Release.Name }}`}}/secrets.yaml
    - secrets/{{`{{ .Release.Name }}`}}/secrets.yaml.gotmpl

releases:
  - name: kubed
    namespace: kube-system
    chart: appscode/kubed
    version: 0.12.0
    <<: *default
  - name: external-dns
    namespace: kube-system
    chart: bitnami/external-dns
    version: 5.0.0
    <<: *default
  - name: nginx-ingress
    namespace: kube-system
    chart: ingress-nginx/ingress-nginx
    version: 2.16.0
    <<: *default
  - name: logging-operator
    namespace: kube-system
    chart: banzicloud-stable/logging-operator
    disableValidation: true
    version: 3.9.0
    <<: *default
  - name: prometheus-operator
    namespace: kube-system
    chart: prometheus-community/kube-prometheus-stack
    disableValidation: true
    version: 15.4.6
    <<: *default
  - name: woodpecker-agent
    namespace: ci
    chart: ./charts/monochart
    <<: *default
  - name: woodpecker-server
    namespace: ci
    chart: cloudposse-incubator/monochart
    version: 0.25.0
    <<: *default
  - name: kube-system-secrets
    namespace: kube-system
    chart: ./charts/secrets
    <<: *default
  - name: shared-secrets
    namespace: shared
    chart: ./charts/secrets
    <<: *default
  - name: notejam-ci-user
    namespace: default
    chart: ./charts/service-account
    <<: *default
  - name: oauth2-proxy
    namespace: kube-system
    chart: stable/oauth2-proxy
    version: 3.1.0
    <<: *default
  - name: cert-manager
    namespace: kube-system
    chart: jetstack/cert-manager
    version: 1.0.4
    disableValidation: true
    <<: *default
  - name: certificates
    namespace: shared
    chart: ./charts/certificates
    disableValidation: true
    needs:
      - kube-system/cert-manager
    <<: *default