controller:
  admissionWebhooks:
    enabled: false
  service:
    externalTrafficPolicy: Cluster
    type: LoadBalancer
  publishService:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9913"
