alertmanager:
  ingress:
    enabled: true
    # pathType: ImplementationSpecific
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: https://auth.chllng.ianduffy.ie/oauth2/start?rd=https://$host$request_uri$is_args$args
      nginx.ingress.kubernetes.io/auth-url: https://auth.chllng.ianduffy.ie/oauth2/auth
    hosts:
    - alertmanager.chllng.ianduffy.ie
    tls:
    -   secretName: certificates-wildcard-cert
        hosts:
        - alertmanager.chllng.ianduffy.ie

grafana:
  grafana.ini:
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Editor
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: https://auth.chllng.ianduffy.ie/oauth2/start?rd=https://$host$request_uri$is_args$args
      nginx.ingress.kubernetes.io/auth-url: https://auth.chllng.ianduffy.ie/oauth2/auth
    # pathType: ImplementationSpecific
    hosts:
    - grafana.chllng.ianduffy.ie
    tls:
    -   secretName: certificates-wildcard-cert
        hosts:
        - grafana.chllng.ianduffy.ie

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      nginx-ingress-controller:
        datasource: Prometheus
        gnetId: 9614
        revision: 1

prometheus:
  ingress:
    enabled: true
    # pathType: ImplementationSpecific
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: https://auth.chllng.ianduffy.ie/oauth2/start?rd=https://$host$request_uri$is_args$args
      nginx.ingress.kubernetes.io/auth-url: https://auth.chllng.ianduffy.ie/oauth2/auth
    hosts:
    - prometheus.chllng.ianduffy.ie
    tls:
    -   secretName: certificates-wildcard-cert
        hosts:
        - prometheus.chllng.ianduffy.ie

  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name 
    - job_name: 'kubernetes-service'
      kubernetes_sd_configs:
      - role: service
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_service_names