{{- $root := . -}}
{{- range $index, $cert := .Values.certificates }}
---
apiVersion: v1
data:
  tls.key: ""
  tls.crt: ""
kind: Secret
metadata:
  annotations:
    kubed.appscode.com/sync: ""
  labels: {{ include "certificates.labels" $root | nindent 4 }}
  name: {{ include "certificates.fullname" $root }}-{{ $cert.name }}
type: kubernetes.io/tls
{{- end }}
