kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "serviceAccount.fullname" . }}
  labels: {{ include "serviceAccount.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccount.fullname" . }}
  namespace: {{ .Release.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "serviceAccount.fullname" . }}
