---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "serviceAccount.fullname" . }}-namespace
  labels: {{ include "serviceAccount.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "serviceAccount.fullname" . }}-cluster
  labels: {{ include "serviceAccount.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "serviceAccount.fullname" . }}
