apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  labels: {{ include "logger.labels" . | nindent 4 }}
  name: {{ include "logger.fullname" . }}
spec:
{{ .Values.output | toYaml | nindent 2}}
